#!/usr/bin/env bash
# This script transfers a file from our client to a server
# -o flag for ssh_option, -i for identity_file
# path_to_file, ip, username, and ssh_key - values of the four
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/;
fi
