#!/usr/bin/env bash
# Install nginx web server

# Update package lists and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create an index.html file containing Hello World!
echo "Hello World!" | sudo tee /var/www/html/index.html

# Replace the default Nginx configration to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx start
