#!/usr/bin/env bash
# Installs and setup haproxy
# 399244-lb-01 configuration

# update packages
apt-get update
# upgrade packages
apt-get upgrade
# install haproxy
apt-get -y install haproxy
# copy to path
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original2
# echo commands
echo "
listen 399244-lb-01
        bind 0:80
        mode http
        stats enable
        balance roundrobin
        option httpclose
        option forwardfor
        server 396785-web-01 100.26.167.206 check port 80
        server 396785-web-02 100.26.161.102 check port 80
" | sudo tee -a /etc/haproxy/haproxy.cfg
# restart
service haproxy restart
