#!/usr/bin/env bash
#configures an Ubuntu server
#Requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

sudo sh -c 'echo "127.0.0.2 localhost" >> /etc/hosts'
sudo sh -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts'
