#!/usr/bin/env bash
# Use an official Apache web server image as the base image
FROM httpd:2.4

# Copy your custom HTML file into the Apache document root
COPY index.html /usr/local/apache2/htdocs/

# Expose port 80 for web traffic
EXPOSE 80
